package ua.edu.znu.app.dto

data class StudentCardDto(
    val firstName: String,
    val secondName: String,
    val lastName: String,
    val birthDate: String,
    val birthPlace: String,
    val faculty: String,
    val studentPhoneNumber: String,
    val addressRegion: String,
    val addressDistrict: String,
    val addressSettlementType: String,
    val addressCity: String,
    val addressStreetType: String,
    val addressStreet: String,
    val addressHouse: String,
    val addressApartment: String,
    val passportSeries: String?,
    val passportNumber: String?,
    val passportIssuer: String,
    val passportUnzdr: String,
    val passportIssuedDate: String,
    val passportValidityDate: String,
    val profilePictureUrl: String?,
    val familyMembers: List<FamilyMemberDto>,
) {
    fun toMap() = mapOf(
        "firstName" to firstName,
        "secondName" to secondName,
        "lastName" to lastName,
        "birthDate" to birthDate,
        "birthPlace" to birthPlace,
        "faculty" to faculty,
        "studentPhoneNumber" to studentPhoneNumber,
        "profilePictureUrl" to profilePictureUrl,
        "addressRegion" to addressRegion,
        "addressDistrict" to addressDistrict,
        "addressSettlementType" to addressSettlementType,
        "addressCity" to addressCity,
        "addressStreetType" to addressStreetType,
        "addressStreet" to addressStreet,
        "addressHouse" to addressHouse,
        "addressApartment" to addressApartment,
        "passportSeries" to passportSeries,
        "passportNumber" to passportNumber,
        "passportUnzdr" to passportUnzdr,
        "passportIssuer" to passportIssuer,
        "passportIssuedDate" to passportIssuedDate,
        "passportValidityDate" to passportValidityDate,
        "familyMembers" to familyMembers,
    )
}
