version: "3.9"

services:
  ktor-app:
    build: .
    container_name: ktor-app
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DB_NAME: database.db
      DB_PATH: /data
    volumes:
      - ./data:/data
